<script setup lang="ts">
import { computed, ref } from "vue";
import { useQueries } from "@tanstack/vue-query";
import { useRoute, useRouter } from "vue-router";
import { ElMessage } from "element-plus";
import { telemetryQueries } from "../api";
import { bytes, count, datetime, duration, percent, shortId } from "../format";
const route = useRoute(); const router = useRouter(); const runId = String(route.params.runId); const tab = ref("overview");
const queries = useQueries({ queries: [
  { queryKey: ["run", runId], queryFn: () => telemetryQueries.getRun(runId) },
  { queryKey: ["run-facts", runId], queryFn: () => telemetryQueries.getRunFacts(runId) },
  { queryKey: ["run-chunks", runId], queryFn: () => telemetryQueries.getRunChunks(runId) },
  { queryKey: ["run-replays", runId], queryFn: () => telemetryQueries.getRunReplays(runId) },
] });
const detail = computed(() => queries.value[0]?.data); const facts = computed(() => queries.value[1]?.data ?? {}); const chunks = computed(() => queries.value[2]?.data?.items ?? []); const replays = computed(() => queries.value[3]?.data?.items ?? []);
const loading = computed(() => queries.value.some((query) => query.isLoading)); const failed = computed(() => queries.value[0]?.isError);
async function copy() { await navigator.clipboard.writeText(runId); ElMessage.success("Run ID 已复制"); }
</script>
<template><div><header class="page-head"><div><el-button text @click="router.push('/runs')">← 返回 Run 列表</el-button><h1>Run 详情</h1><p class="mono">{{ runId }} <el-button text size="small" @click="copy">复制</el-button></p></div></header>
  <el-alert v-if="failed" title="Run 不存在或无法读取" type="error" show-icon/><section v-else class="panel" v-loading="loading"><el-tabs v-model="tab">
    <el-tab-pane label="概况" name="overview"><div v-if="detail" class="facts-grid"><div class="fact"><label>Agent</label><strong>{{ detail.agentType === 'claude_code' ? 'Claude Code' : 'Codex' }}</strong></div><div class="fact"><label>Agent 版本</label><strong>{{ detail.sourceVersion }}</strong></div><div class="fact"><label>解析器版本</label><strong>{{ detail.activeParserVersion ?? '待解析' }}</strong></div><div class="fact"><label>JSONL 行数</label><strong>{{ count(detail.totalLines) }}</strong></div><div class="fact"><label>合法 / 非法行</label><strong>{{ count(detail.validLines) }} / {{ count(detail.invalidLines) }}</strong></div><div class="fact"><label>未知类型行</label><strong>{{ count(detail.unknownTypeLines) }}</strong></div><div class="fact"><label>事件开始</label><strong>{{ datetime(detail.firstTimestamp) }}</strong></div><div class="fact"><label>事件结束</label><strong>{{ datetime(detail.lastTimestamp) }}</strong></div><div class="fact"><label>数据量</label><strong>{{ detail.chunkCount }} 块 · {{ bytes(detail.byteCount) }}</strong></div></div></el-tab-pane>
    <el-tab-pane label="资源与上下文" name="resources"><h3>消息与 Token</h3><div class="facts-grid"><div class="fact"><label>消息记录</label><strong>{{ count(facts.messages?.total) }}</strong></div><div class="fact"><label>输入 Token</label><strong>{{ count(facts.tokens?.input_tokens) }}</strong></div><div class="fact"><label>输出 Token</label><strong>{{ count(facts.tokens?.output_tokens) }}</strong></div><div class="fact"><label>缓存读取 Token</label><strong>{{ count(facts.tokens?.cache_read_input_tokens) }}</strong></div><div class="fact"><label>缓存写入 Token</label><strong>{{ count(facts.tokens?.cache_write_or_creation_input_tokens) }}</strong></div><div class="fact"><label>宿主记录跨度</label><strong>{{ detail?.firstTimestamp && detail?.lastTimestamp ? duration(Date.parse(detail.lastTimestamp)-Date.parse(detail.firstTimestamp)) : '暂无数据' }}</strong></div></div>
      <h3>上下文压缩</h3><div class="facts-grid"><div class="fact"><label>压缩总次数</label><strong>{{ count(facts.context?.compactions?.total) }}</strong></div><div class="fact"><label>自动 / 手动 / 未知</label><strong>{{ count(facts.context?.compactions?.byTrigger?.auto) }} / {{ count(facts.context?.compactions?.byTrigger?.manual) }} / {{ count(facts.context?.compactions?.byTrigger?.unknown) }}</strong></div><div class="fact"><label>上下文上限</label><strong :class="facts.context?.window?.observed ? '' : 'unknown'">{{ facts.context?.window?.observed ? count(facts.context.window.latestTokens) + ' Token' : '当前数据源未提供' }}</strong></div></div></el-tab-pane>
    <el-tab-pane label="工具与子代理" name="tools"><h3>工具调用</h3><div class="facts-grid"><div class="fact"><label>调用次数</label><strong>{{ count(facts.tools?.calls) }}</strong></div><div class="fact"><label>明确成功 / 失败</label><strong>{{ count(facts.tools?.successes) }} / <span class="danger">{{ count(facts.tools?.failures) }}</span></strong></div><div class="fact"><label>不可判定</label><strong>{{ count(facts.tools?.unknown_results) }}</strong></div><div class="fact"><label>状态覆盖率</label><strong>{{ percent(facts.tools?.status_coverage) }}</strong></div><div class="fact"><label>工具耗时 P50 / P90</label><strong>{{ duration(facts.tools?.duration?.p50_ms) }} / {{ duration(facts.tools?.duration?.p90_ms) }}</strong></div><div class="fact"><label>去除并发后的经过时间</label><strong>{{ duration(facts.tools?.duration?.wall_clock_ms) }}</strong></div></div><p class="muted">明确失败是实际失败数的下界，必须结合状态覆盖率理解。</p>
      <el-table :data="Object.entries(facts.tools?.byTool ?? {}).map(([name,value])=>({name,...value}))" size="small"><el-table-column prop="name" label="工具"/><el-table-column prop="calls" label="调用"/><el-table-column prop="successes" label="明确成功"/><el-table-column prop="failures" label="明确失败"/><el-table-column label="覆盖率"><template #default="{row}">{{ percent(row.status_coverage) }}</template></el-table-column></el-table>
      <h3>子代理</h3><div class="facts-grid"><div class="fact"><label>子代理数量</label><strong>{{ count(facts.subagents?.count) }}</strong></div><div class="fact"><label>最大层级</label><strong>{{ count(facts.subagents?.max_depth) }}</strong></div><div class="fact"><label>子代理消息</label><strong>{{ count(facts.subagents?.messages?.total) }}</strong></div><div class="fact"><label>子代理输入 Token</label><strong>{{ count(facts.subagents?.tokens?.input_tokens) }}</strong></div><div class="fact"><label>子代理工具调用</label><strong>{{ count(facts.subagents?.tools?.calls) }}</strong></div></div>
      <el-table v-if="facts.subagents?.sessions?.length" :data="facts.subagents.sessions" size="small" style="margin-top:16px"><el-table-column label="Session"><template #default="{row}"><span class="mono">{{ shortId(row.agentSessionId) }}</span></template></el-table-column><el-table-column label="父 Session"><template #default="{row}"><span class="mono">{{ row.parentAgentSessionId ? shortId(row.parentAgentSessionId) : '主会话' }}</span></template></el-table-column><el-table-column prop="messages.total" label="消息"/><el-table-column prop="tools.calls" label="工具调用"/></el-table></el-tab-pane>
    <el-tab-pane label="采集与解析" name="collection"><h3>原始数据块</h3><el-table :data="chunks" size="small"><el-table-column prop="generation" label="代次" width="70"/><el-table-column prop="startOffset" label="起点"/><el-table-column prop="endOffset" label="终点"/><el-table-column label="大小"><template #default="{row}">{{ bytes(row.byteCount) }}</template></el-table-column><el-table-column prop="parserStatus" label="解析状态"/><el-table-column label="原始文件"><template #default="{row}">{{ row.rawPresent ? '存在' : '缺失' }}</template></el-table-column></el-table><h3>重放历史</h3><el-table :data="replays" size="small"><el-table-column prop="targetVersion" label="目标版本"/><el-table-column prop="status" label="状态"/><el-table-column prop="totalChunks" label="数据块"/><el-table-column label="开始时间"><template #default="{row}">{{ datetime(row.startedAt) }}</template></el-table-column><el-table-column prop="failureCode" label="失败原因"/></el-table><div v-if="!replays.length" class="empty">没有重放记录</div></el-tab-pane>
  </el-tabs></section></div></template>
<style scoped>h3{margin:24px 0 14px}.el-tab-pane>h3:first-child{margin-top:8px}</style>
